apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: home-assistant
  labels:
    app: mosquitto
data:
  password.txt: |
    mqtt-user:$7$1000$dBulLnt/TffI6jHmsHCR0Se7eKza2rxzKTtYGsCGix/JyyFyk6tSlaoMF7KTp5/KpjpZELPqj+3PobyoELGYzA==$VYsicIH3J+jKkS/N3l46C6smTeMKFIyio8lkoKO7fcnMRdKzJvxa3iwVZMiJqn/lTeb0tYcO6CBRjDmMXty5iw==
