apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-assistant
data: #    password_file /mosquitto/password/password.txt
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout

    listener 8883
    protocol mqtt

    listener_allow_anonymous true
